const EP={dados:[],arquivo:"",resumo:null,g:{d:null,a:null,u:null}};
const C={data:"A",r47:"B",r76:"C",rt:"D",s47:"AO",s76:"AP",st:"AQ",b47:"BS",b76:"BT",bt:"BU"};
document.addEventListener("DOMContentLoaded",()=>{const $=id=>document.getElementById(id); $("arquivoProducao").addEventListener("change",carregar); $("btnAtualizarProducao").onclick=atualizar; $("filtroMetaProducao").onchange=atualizar; $("filtroUsinaProducao").onchange=atualizar; $("btnGerarPdfProducao").onclick=gerarPDF; $("btnEnviarEmailProducao").onclick=enviarEmail; cabecalhoTabela();});
const $=id=>document.getElementById(id), num=v=>{if(typeof v==="number")return isFinite(v)?v:0;if(v==null||v==="")return 0;let s=String(v).trim().replace(/\s/g,"");if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");return isFinite(+s)?+s:0}, col=(r,c)=>num(r[XLSX.utils.decode_col(c)]);
function normal(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase()}
function data(v){if(v instanceof Date)return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?new Date(d.y,d.m-1,d.d):null}const m=String(v||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);return null}
function texto(id,v){const e=$(id);if(e)e.textContent=v} function carga(t,s){texto("tituloCarregamentoProducao",t);texto("textoCarregamentoProducao",s);$("overlayCarregamentoProducao").classList.remove("oculto")} function fimCarga(){$("overlayCarregamentoProducao").classList.add("oculto")}
function aviso(t,c="sucesso"){$("avisoProducao").textContent=t;$("avisoProducao").className="aviso-producao aviso-"+c;$("avisoProducao").style.display="block"}
function carregar(ev){const f=ev.target.files[0];if(!f)return;if(typeof XLSX==="undefined")return aviso("Biblioteca do Excel não carregada.","erro");EP.arquivo=f.name;texto("nomeArquivoProducao","Preparando "+f.name);carga("Carregando planilha","Lendo "+f.name+"...");const rd=new FileReader();rd.onload=e=>setTimeout(()=>{try{const wb=XLSX.read(new Uint8Array(e.target.result),{type:"array",cellDates:true,cellStyles:false,cellFormula:false,sheets:["Controle Produção"]});const nome=wb.SheetNames.find(n=>normal(n)===normal("Controle Produção"));if(!nome)throw Error('A aba "Controle Produção" não foi encontrada.');const sh=wb.Sheets[nome];let fim=4;for(let i=4;i<=10000;i++){const c=sh["A"+i];if(c&&c.v!==""&&c.v!=null)fim=i}const rows=XLSX.utils.sheet_to_json(sh,{header:1,raw:true,defval:null,blankrows:false,range:"A1:DQ"+fim});EP.dados=[];for(let i=3;i<rows.length;i++){const r=rows[i],dt=data(r?.[0]);if(!dt)continue;const x={data:dt,r47:col(r,C.r47),r76:col(r,C.r76),rt:col(r,C.rt),s47:col(r,C.s47),s76:col(r,C.s76),st:col(r,C.st),b47:col(r,C.b47),b76:col(r,C.b76),bt:col(r,C.bt)};if(!x.rt)x.rt=x.r47+x.r76;if(!x.st)x.st=x.s47+x.s76;if(!x.bt)x.bt=x.b47+x.b76;EP.dados.push(x)}if(!EP.dados.length)throw Error("Nenhum dado válido encontrado.");EP.dados.sort((a,b)=>a.data-b.data);texto("nomeArquivoProducao",f.name);periodoInicial();atualizar();fimCarga();aviso("Planilha carregada: "+f.name)}catch(err){console.error(err);fimCarga();aviso("Erro: "+err.message,"erro")}},100);rd.onerror=()=>{fimCarga();aviso("Falha na leitura do arquivo.","erro")};rd.readAsArrayBuffer(f)}
function periodoInicial(){const v=EP.dados.filter(x=>x.rt||x.r47||x.r76),u=v.at(-1)||EP.dados.at(-1),fim=new Date(u.data),ini=new Date(fim.getFullYear(),fim.getMonth(),1);$("dataInicialProducao").value=iso(ini);$("dataFinalProducao").value=iso(fim)}
function lerData(id){const s=$(id).value;if(!s)return null;const p=s.split("-");return new Date(+p[0],+p[1]-1,+p[2])} function iso(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
function valores(x){const u=$("filtroUsinaProducao").value;return u==="47"?{r:x.r47,s:x.s47,b:x.b47}:u==="76"?{r:x.r76,s:x.s76,b:x.b76}:{r:x.rt,s:x.st,b:x.bt}}
function resumo(d){let z={r:0,s:0,b:0,r47:0,r76:0};d.forEach(x=>{const v=valores(x);z.r+=v.r;z.s+=v.s;z.b+=v.b;z.r47+=x.r47;z.r76+=x.r76});z.as=z.s?z.r/z.s*100:0;z.ab=z.b?z.r/z.b*100:0;z.ds=z.r-z.s;z.db=z.r-z.b;return z}
function atualizar(){if(!EP.dados.length)return;const a=lerData("dataInicialProducao"),b=lerData("dataFinalProducao");if(!a||!b||a>b)return aviso("Verifique as datas.","erro");const d=EP.dados.filter(x=>x.data>=a&&x.data<=b);if(!d.length)return aviso("Sem dados no período.","erro");const z=EP.resumo=resumo(d),m=$("filtroMetaProducao").value;["MetaSop","AderenciaSop"].forEach(n=>$("cardContainer"+n).classList.toggle("oculto",m==="bap"));["MetaBap","AderenciaBap"].forEach(n=>$("cardContainer"+n).classList.toggle("oculto",m==="sop"));texto("cardProducaoRealizada",ton(z.r));texto("cardMetaSop",ton(z.s));texto("cardMetaBap",ton(z.b));texto("cardAderenciaSop",pct(z.as));texto("cardAderenciaBap",pct(z.ab));texto("cardUsina47",ton(z.r47));texto("cardUsina76",ton(z.r76));const dif=m==="bap"?z.db:z.ds;texto("tituloDiferencaProducao",m==="bap"?"Diferença para BAP":"Diferença para S&OP");texto("cardDiferencaProducao",sinal(dif));$("cardDiferencaProducao").className=dif>=0?"positivo":"negativo";graficos(d,m);mensal(d,m);anual(d);texto("periodoDashboardProducao","Período: "+br(a)+" a "+br(b));texto("ultimaAtualizacaoProducao","Arquivo: "+EP.arquivo)}
function dadosLinha(d,m,ac=false){let ar=0,as=0,ab=0,ds=[{type:ac?"line":"bar",label:ac?"Real":"Realizado",data:d.map(x=>{const v=valores(x).r;ar+=v;return ac?ar:v}),backgroundColor:"#390460",borderColor:"#390460",borderWidth:ac?2.5:1,borderRadius:4,pointRadius:1.5,pointStyle:ac?"line":"rectRounded",order:ac?0:3}];if(m!=="bap")ds.push({type:"line",label:"S&OP",data:d.map(x=>{const v=valores(x).s;as+=v;return ac?as:v}),borderColor:"#72b82b",backgroundColor:"#72b82b",borderWidth:2,pointRadius:1.5,pointStyle:"line",tension:.2,order:1});if(m!=="sop")ds.push({type:"line",label:"BAP",data:d.map(x=>{const v=valores(x).b;ab+=v;return ac?ab:v}),borderColor:"#e99522",backgroundColor:"#e99522",borderWidth:2,borderDash:[7,4],pointRadius:1.5,pointStyle:"line",tension:.2,order:1});return ds}
function opcoes(stacked=false){return{responsive:true,maintainAspectRatio:false,devicePixelRatio:2,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"top",align:"start",labels:{usePointStyle:true,pointStyleWidth:25,boxWidth:25,boxHeight:2,padding:16,color:"#352d39",font:{size:12,weight:"600"}}},tooltip:{callbacks:{label:c=>c.dataset.label+": "+ton(c.parsed.y)}}},scales:{x:{stacked,grid:{display:false},ticks:{font:{size:10,weight:"600"},maxRotation:55}},y:{stacked,beginAtZero:true,grid:{color:"rgba(45,1,77,.08)"},ticks:{font:{size:11,weight:"600"},callback:n=>fmt(n)}}}}}
function graficos(d,m){["d","a","u"].forEach(k=>{if(EP.g[k])EP.g[k].destroy()});const labels=d.map(x=>curta(x.data));EP.g.d=new Chart($("graficoProducaoDiaria"),{data:{labels,datasets:dadosLinha(d,m,false)},options:opcoes()});EP.g.a=new Chart($("graficoProducaoAcumulada"),{type:"line",data:{labels,datasets:dadosLinha(d,m,true)},options:opcoes()});EP.g.u=new Chart($("graficoProducaoUsinas"),{type:"bar",data:{labels,datasets:[{label:"Usina 47",data:d.map(x=>x.r47),backgroundColor:"#390460",stack:"p",borderRadius:3},{label:"Usina 76",data:d.map(x=>x.r76),backgroundColor:"#92d050",stack:"p",borderRadius:3}]},options:opcoes(true)})}
function mensal(d,m){const a={};d.forEach(x=>{const k=x.data.getFullYear()+"-"+String(x.data.getMonth()+1).padStart(2,"0");if(!a[k])a[k]={data:new Date(x.data.getFullYear(),x.data.getMonth(),1),r:0,s:0,b:0};const v=valores(x);a[k].r+=v.r;a[k].s+=v.s;a[k].b+=v.b});let h="<tr><th>Mês</th><th>Realizado</th>";if(m!=="bap")h+="<th>S&OP</th><th>Aderência</th><th>Desvio</th>";if(m!=="sop")h+="<th>BAP</th><th>Aderência</th><th>Desvio</th>";$("cabecalhoTabelaProducao").innerHTML=h+"</tr>";$("corpoTabelaProducao").innerHTML=Object.values(a).map(x=>{let r=`<tr><td><strong>${mes(x.data)}</strong></td><td><strong>${ton(x.r)}</strong></td>`;if(m!=="bap")r+=`<td>${ton(x.s)}</td><td>${pct(x.s?x.r/x.s*100:0)}</td><td class="${x.r-x.s>=0?'positivo':'negativo'}">${sinal(x.r-x.s)}</td>`;if(m!=="sop")r+=`<td>${ton(x.b)}</td><td>${pct(x.b?x.r/x.b*100:0)}</td><td class="${x.r-x.b>=0?'positivo':'negativo'}">${sinal(x.r-x.b)}</td>`;return r+"</tr>"}).join("")}
function cabecalhoTabela(){$("cabecalhoTabelaProducao").innerHTML="<tr><th>Mês</th><th>Realizado</th><th>S&OP</th><th>Aderência</th><th>Desvio</th><th>BAP</th><th>Aderência</th><th>Desvio</th></tr>"}
function anual(d){const a={};d.forEach(x=>(a[x.data.getFullYear()]??=[]).push(x));$("resumoAnualProducao").innerHTML=Object.entries(a).map(([ano,v])=>{const z=resumo(v);return `<article class="ano-resumo-producao"><div class="cabecalho-ano-resumo-producao"><small>ANO</small><strong>${ano}</strong><span>Período filtrado</span></div><div class="metricas-ano-resumo-producao">${met("Realizado",ton(z.r),"roxo")}${met("S&OP",ton(z.s),"verde")}${met("Ader. S&OP",pct(z.as),z.as>=100?"verde":"vermelho")}${met("Desvio S&OP",sinal(z.ds),z.ds>=0?"verde":"vermelho")}${met("BAP",ton(z.b),"laranja")}${met("Ader. BAP",pct(z.ab),z.ab>=100?"verde":"vermelho")}${met("Desvio BAP",sinal(z.db),z.db>=0?"verde":"vermelho")}</div></article>`}).join("")}
function met(t,v,c){return `<section class="metrica-${c}"><span>${t}</span><strong>${v}</strong></section>`}
async function gerarPDF(){if(!EP.resumo)return aviso("Carregue a planilha.","erro");if(!window.jspdf||typeof html2canvas==="undefined")return aviso("Bibliotecas do PDF não carregadas.","erro");carga("Gerando PDF","Preparando página 1 de 2...");document.body.classList.add("gerando-pdf-producao");try{await new Promise(r=>setTimeout(r,600));const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4",compress:true});const c1=await captura("cardsProducaoUsina"),c2=await captura("gridGraficosProducao");cabPdf(pdf,"Resumo executivo e evolução da produção");secoesPdf(pdf,[c1,c2]);pdf.addPage("a4","landscape");texto("textoCarregamentoProducao","Preparando página 2 de 2...");const c3=await captura("gridInferiorProducao"),c4=await captura("blocoResumoAnualProducao");cabPdf(pdf,"Produção por usina e resumos do período");secoesPdf(pdf,[c3,c4]);pdf.save(`Relatorio_Producao_${$("dataInicialProducao").value}_a_${$("dataFinalProducao").value}.pdf`);aviso("PDF gerado em duas páginas.")}catch(e){console.error(e);aviso("Erro no PDF: "+e.message,"erro")}finally{document.body.classList.remove("gerando-pdf-producao");fimCarga()}}
async function captura(id){const e=$(id);return html2canvas(e,{scale:2.5,useCORS:true,backgroundColor:"#fff",logging:false,width:e.scrollWidth,height:e.scrollHeight,windowWidth:e.scrollWidth,windowHeight:e.scrollHeight})}
function cabPdf(pdf,t){const w=pdf.internal.pageSize.getWidth();pdf.setFillColor(45,1,77);pdf.rect(0,0,w,24,"F");pdf.setTextColor(255);pdf.setFont("helvetica","bold");pdf.setFontSize(15);pdf.text("PORTAL FVO · PRODUÇÃO DA USINA",10,10);pdf.setFontSize(10);pdf.text(t,10,18);pdf.setFont("helvetica","normal");pdf.setFontSize(8);pdf.text(periodo()+" · "+nomeUsina()+" · "+nomeMeta(),w-10,10,{align:"right"});pdf.text("Planilha: "+EP.arquivo,w-10,17,{align:"right"})}
function secoesPdf(pdf,cs){const w=pdf.internal.pageSize.getWidth(),h=pdf.internal.pageSize.getHeight(),mx=8,top=29,bot=8,gap=5,aw=w-2*mx,ah=h-top-bot,mw=Math.max(...cs.map(c=>c.width)),total=cs.reduce((s,c)=>s+c.height,0)+gap*(cs.length-1)*mw/aw,sc=Math.min(aw/mw,ah/total);let y=top;cs.forEach(c=>{const iw=c.width*sc,ih=c.height*sc;pdf.addImage(c.toDataURL("image/png",1),"PNG",(w-iw)/2,y,iw,ih,undefined,"FAST");y+=ih+gap})}
function enviarEmail(){if(!EP.resumo)return aviso("Carregue a planilha.","erro");const z=EP.resumo,ass="Relatório de Produção - "+periodo(),cor=`Olá,\n\nResumo da produção da usina.\n\nPeríodo: ${periodo()}\nUsina: ${nomeUsina()}\nRealizado: ${ton(z.r)}\nS&OP: ${ton(z.s)}\nAderência S&OP: ${pct(z.as)}\nDesvio S&OP: ${sinal(z.ds)}\nBAP: ${ton(z.b)}\nAderência BAP: ${pct(z.ab)}\nDesvio BAP: ${sinal(z.db)}\n\nAnexe o PDF gerado.`;location.href=`mailto:luiz.campos@br.cmoc.com,thais.gilvana@br.cmoc.com?subject=${encodeURIComponent(ass)}&body=${encodeURIComponent(cor)}`}
const fmt=n=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(n||0),ton=n=>fmt(n)+" t",pct=n=>new Intl.NumberFormat("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1}).format(n||0)+"%",sinal=n=>(n>0?"+":"")+ton(n),br=d=>d.toLocaleDateString("pt-BR"),curta=d=>d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),mes=d=>d.toLocaleDateString("pt-BR",{month:"short",year:"numeric"}).replace(".",""),periodo=()=>{const a=lerData("dataInicialProducao"),b=lerData("dataFinalProducao");return a&&b?br(a)+" a "+br(b):"Período não informado"},nomeUsina=()=>$("filtroUsinaProducao").value==="47"?"Usina 47":$("filtroUsinaProducao").value==="76"?"Usina 76":"Consolidado",nomeMeta=()=>$("filtroMetaProducao").value==="sop"?"S&OP":$("filtroMetaProducao").value==="bap"?"BAP":"S&OP + BAP";
